# Generated by Django 4.1.7 on 2023-04-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
            ],
        ),
    ]
